name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js Version 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci
